{% set name = "zope.deprecation" %}
{% set version = "5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b7c32d3392036b2145c40b3103e7322db68662ab09b7267afe1532a9d93f640f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - zope
    - zope.deprecation

about:
  home: https://github.com/zopefoundation/zope.deprecation
  license: ZPL 2.1
  license_family: OTHER
  license_file: LICENSE.txt
  summary: Zope Deprecation Infrastructure
  doc_url: https://zopedeprecation.readthedocs.io/
  dev_url: https://github.com/zopefoundation/zope.deprecation

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
