travis:
  secure:
    BINSTAR_TOKEN: RVlTz1M67/0iKRoMaGv4HJAV85bjEhNY4dNBgrUXU+wdbWoSeTh3tv6MdYQXOe1dDgEZoX2hP3Fb/m7T2A05MxI/Tvv7kdEqx3MrxzAed0HgPcjhhIUskjwtDq1uuE3nmGIJ+5fSCePdYTvnJPGHtZlJi6ICSB6tUnj8XcYEhPoXNOiq6VM+k5zROISsKjNMqFc8fYMyo/6JL8osW2kWOYFEI/eQvk3bHZjg4TnG1KotqMdixnr7ekcF2j7Hyry2vZh2LBY9IUDZH+WP2hgzEGEoou5PznTmGzWnn5GYEZ8DxCIpkBQyHzjjNzEB3fsB/PLFEvo+twgdbus6e+1gInovL2/vZ6ZuGcWHaUMzcP0Z3K0t9OfMSCaGskfsHiFWBsap/U5YjsqQoq2SDykgsElCs6v2ITWxT04UTxSDVOAdiW3FGQisD+eX4CoLc/YEPT6Jv30CvaeZ5oOEiZsagtLxDMCxcbyj4yJtxlZpKb64zHt0q6bAc9cG/AX5H4tOCitJB+4gN6cPVtI9UOK3dpmIsOqBzbicDZ+Ud8rjZywH9G3M3miPDVOweh6gj0jpRmG72ITI9eY8YBeED4yRAGzOdpZCUOd1XUjq/C6iihOkIiEBNPKeLhM9EmPhdjdAtxcjRp4eQYEZEEEYnZFAW+OrSego2oDFJN/IPFEgG54=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
